name: GitHub Release From Changelog
description: Creates a GitHub Release using Changelog file
inputs:
  tag:
    description: The tag to use for the release. Omit if triggering from a tag event.
    required: false
    default: ${{ github.ref }}
  filename:
    description: Optional filename of changelog (default searches across a range of changelog filenames).
    required: false
    default: ""
outputs:
  tag:
    description: The resolved tag name used by the action
    value: ${{ steps.tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - run: ruby ${{ github.action_path }}/main.rb ${{ inputs.tag }}
      env:
        FILENAME: ${{ inputs.filename }}
      shell: bash
